name: dir_contents_diff
publish_to: none

# Required for workspace support.
environment:
  sdk: ^3.5.0-294.0.dev

# This package is managed as part of the engine workspace.
resolution: workspace

dev_dependencies:
  engine_repo_tools: any
  path: any
  test: any
