# Copyright 2023 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: Minimal workflow to test github action token

on:
  workflow_dispatch

permissions: write-all

jobs:
  minimal_token_test:
    name: minimal_token_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Flutter Repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          repository: flutter/flutter
          token: ${{ github.token }}
          path: flutter
          ref: master
          fetch-depth: 0
      - name: Write a random file
        run: |
          cd flutter
          touch empty.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          path: flutter
          commit-message: blah
          committer: GitHub <noreply@github.com>
          token: ${{ secrets.FLUTTERACTIONSBOT_CP_TOKEN }}
          labels: |
            cp: review
          title: '[github actions] testing purposes'
          reviewers: xilaizhang
